
POST http://localhost:8080/cooperation/insert
Content-Type: application/json

{
  "cooperation": {
    "photo": "XXX",
    "content": "XXX",
    "type": "0",
    "title": "xxx"
  }
}

###
GET http://localhost:8080/cooperation/1

###
DELETE http://localhost:8080/cooperation/1

###
GET http://localhost:8080/cooperation/list?page=1&limit=5

###
